### ISSUE TITLE
Incorrect version number on https://tdg.docbook.org/

### ISSUE THREAD

**Issue by gemmaro** [docbook/docbook.org#51]
The following is in [the "DocBook 5: The Definitive Guide" section](https://tdg.docbook.org/#defguide), but I think the version is correctly 5.1.3.

> [DocBook: TDG 1.5.3](https://tdg.docbook.org/tdg/5.1/) for DocBook V5.1

Sorry if this is the wrong place to report this. I could not find where the source of this page is located.

**Comment by ndw** [comment]
No, I don't think so. The documentation version and the schema version aren't synchronized. If you follow the link for the 5.1 version of the guide, I think you'll find it says it's version "1.5.3".

For the 5.2 series, I decided that was confusing :-) and now it's 5.2.x.
