### ISSUE TITLE
Update pages with info about V5.1

### ISSUE THREAD

**Issue by kosek** [docbook/docbook.org#8]
V5.1 is already finished (see https://lists.oasis-open.org/archives/docbook-tc/201512/msg00011.html) but this is not reflected on pages. 

Pages to update include:
- http://docbook.org/schemas/5x.html 
  (add link to 5.1 schemas and committee specification; probably link to later CR versions as well)
- http://docbook.org/schemas/
  (mention V5.1)

**Comment by kosek** [comment]
Anyway more updates will be needed. Since I have created PR DocBook become OASIS Standard. Sigh!

**Comment by l2dy** [comment]
Older versions have a zip file like http://docbook.org/xml/5.0/docbook-5.0.zip. Will 5.1 get one too?

**Comment by bobstayton** [comment]
I updated the docbook.org pages for 5.1.

**Comment by l2dy** [comment]
The catalog file in `docbook-v5.1-os.zip` contains `5.1CR4`, is it the equivalent of https://docbook.org/xml/5.0/docbook-5.0.zip?

```
<!-- This is the source format for the catalog; replace 5.1CR4 with the appropriate
     versions before publishing it! -->

<uri name="http://www.oasis-open.org/docbook/xml/5.1CR4/docbook.nvdl" uri="docbook.nvdl"/>
<uri name="http://www.oasis-open.org/docbook/xml/5.1CR4/rng/assembly.rnc" uri="rng/assembly.rnc"/>
<uri name="http://www.oasis-open.org/docbook/xml/5.1CR4/rng/assembly.rng" uri="rng/assembly.rng"/>
```
