### ISSUE TITLE
Recover How-to document

### ISSUE THREAD

**Issue by kosek** [docbook/docbook.org#9]
Content at http://docbook.org/docs/howto/ is no longer available and returns 404.

**Comment by kosek** [comment]
OK, document is there (at http://docbook.org/docs/howto/howto.html), so only URL above is returning 404 and it's linked from other pages. 

It seems that problem is that GH pages are ignoring .htaccess and DirectoryIndex option. In the worst case we can update build script to copy howto.html into index.html to make this working.

**Comment by ndw** [comment]
Fixing now

**Comment by ndw** [comment]
The transclusion document is also "missing"; should we add a pointer to that as well?

**Comment by kosek** [comment]
Yes, I have already added issue #11 for this.

**Comment by ndw** [comment]
FYI: I added an index page that points to the documents:
1. There's no htaccess on gh-pages
2. The build script uses webpage.xsl for all the built pages. That's possibly not appropriate for standalone documents.
